name: Daily Commit Bot

on:
  schedule:
    - cron: "0 14 * * *"

jobs:
  update_date_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Year Directory if Needed
        run: |
          YEAR=$(date +%Y)
          mkdir -p ${YEAR}

      - name: Update Date in Monthly File
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          FILE="${YEAR}/${MONTH}.md"
          echo "- [x] $(date +%Y-%m-%d) commit completed 👌" >> ${FILE}

      - name: Commit and Push
        run: |
          git config --global user.name '${{ secrets.USER_NAME }}'
          git config --global user.email '${{ secrets.USER_EMAIL }}'
          git add ${YEAR}/${MONTH}.md
          git commit -m "commit completed today!"
          git push
